name = "albionstatus-api"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "1352b1a4f604a54c8862bec20881b0fb"
compatibility_flags = ["nodejs_compat_v2"]

[site]
bucket = ".output/public"

[vars]

# The necessary secrets are:
# - MONGODB_URI