name = "albionstatus-scraper"
main = "index.ts"
compatibility_date = "2025-12-16"
account_id = "1352b1a4f604a54c8862bec20881b0fb"

compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [ "* * * * *" ]

[vars]
# Needed secrets are
# - MONGODB_URI