name: cloudflare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter api build

      - name: Publish API to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'packages/api'
          apiToken: ${{ secrets.CF_API_TOKEN }}

      - name: Publish Scraper to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'packages/scrape-and-tweet'
          apiToken: ${{ secrets.CF_API_TOKEN }}
    